#!/usr/bin/env python3

import re
import sys
from pathlib import Path

# ---------------------------------------------------------
# SANITIZER HELPER
# ---------------------------------------------------------
def sanitize(text: str) -> str:
    # 1. Protect LaTeX math blocks: \( ... \) or $ ... $
    math_pattern = r"(\\\(.+?\\\))|(\$.+?\$)"
    parts = re.split(math_pattern, text)
    
    replacements = {
        "&": r"\&",
        "%": r"\%",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "◊": r"\ensuremath{\diamond}",
        "♦": r"\ensuremath{\diamond}",
        "■": r"\ensuremath{\blacksquare}",
    }

    processed_parts = []
    for part in parts:
        if part is None:
            continue
        
        if part.startswith("\\(") or part.startswith("$"):
            processed_parts.append(part)
        else:
            for k, v in replacements.items():
                part = part.replace(k, v)
            
            part = re.sub(r"(?<!\\)\$", r"\\$", part)
            part = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", part)
            part = re.sub(r"\*(?!\*)([^\n]+?)\*", r"\\emph{\1}", part)
            processed_parts.append(part)

    return "".join(processed_parts).strip()

# ---------------------------------------------------------
# MAIN
# ---------------------------------------------------------
def main():
    if len(sys.argv) != 2:
        print("Usage: python build_mc_tex.py <version>")
        sys.exit(1)

    version = sys.argv[1].upper()

    # ---------------------------------------------------------
    # ANCHOR PATHING
    # ---------------------------------------------------------
    # Anchors the script to the project root (midterm2/)
    BASE_DIR = Path(__file__).resolve().parent.parent
    INPUTS_DIR = BASE_DIR / "inputs"
    BUILD_DIR = BASE_DIR / "build"
    
    # 1. Content Inputs (Work-in-progress files from the build zone)
    md_file = BUILD_DIR / "shuffled" / f"mc_{version}.md"
    if not md_file.exists():
        raise FileNotFoundError(f"❌ Markdown file not found: {md_file}")

    # FR files generated by build_fr_tex.py
    FR_FILE = BUILD_DIR / f"fr_{version}.tex"
    if FR_FILE.exists():
        fr_content = FR_FILE.read_text(encoding="utf-8")
    else:
        fr_content = "% (No free response questions found for this version)"

    # 2. Static Templates (Looked for in the machinery zone)
    # Updated to 'exam_template.tex' to match Gold Standard naming
    TEMPLATE = INPUTS_DIR / "exam_template.tex"
    if not TEMPLATE.exists():
        # Fallback if you haven't renamed 'template.tex' yet
        TEMPLATE = INPUTS_DIR / "template.tex"
        if not TEMPLATE.exists():
            raise FileNotFoundError(f"❌ Missing LaTeX template in {INPUTS_DIR}")

    BACK_FILE = INPUTS_DIR / "back_page.tex"
    if BACK_FILE.exists():
        back_content = BACK_FILE.read_text(encoding="utf-8")
    else:
        back_content = "% (No back-page content found in inputs/)"

    # 3. Output (The 'cooking' subfolder for LaTeX compilation)
    out_dir = BUILD_DIR / "cooking"
    out_dir.mkdir(parents=True, exist_ok=True)

    # ---------------------------------------------------------
    # PARSE MARKDOWN (Logic preserved)
    # ---------------------------------------------------------
    raw = md_file.read_text(encoding="utf-8")

    blocks = re.split(
        r"^##\s+Question\s+\d+\s*$",
        raw,
        flags=re.MULTILINE
    )[1:]

    questions_tex = []

    for block in blocks:
        lines = [ln.rstrip() for ln in block.strip().splitlines()]
        stem_lines = []
        choices = []

        for ln in lines:
            ln = ln.strip()
            if not ln or ln.startswith("<" + "!--") or ln == "---":
                continue

            # Identify choices (- A. Text)
            m = re.match(r"-\s*([a-dA-D])[.)]\s+(.*)", ln)
            if m:
                choices.append(r"    \item " + sanitize(m.group(2)))
            else:
                stem_lines.append(ln)

        if len(choices) != 4:
            continue

        stem = sanitize(" ".join(stem_lines))

        qtex = (
            f"  \\question{{{stem}}}\n"
            f"  \\begin{{choices}}\n"
            + "\n".join(choices) +
            "\n  \\end{choices}\n"
        )
        questions_tex.append(qtex)

    if not questions_tex:
        raise RuntimeError("Parsed zero valid questions.")

    mc_content = "\n\n".join(questions_tex)

    # ---------------------------------------------------------
    # INSERT INTO TEMPLATE
    # ---------------------------------------------------------
    template = TEMPLATE.read_text(encoding="utf-8")

    final_tex = (
        template
        .replace("VERSION_PLACEHOLDER", version)
        .replace("MC_CONTENT_PLACEHOLDER", mc_content)
        .replace("FR_CONTENT_PLACEHOLDER", fr_content)
        .replace("BACK_CONTENT_PLACEHOLDER", back_content)
    )

    out_file = out_dir / f"mc_{version}.tex"
    out_file.write_text(final_tex, encoding="utf-8")

    print(f"✅ Created LaTeX: build/cooking/mc_{version}.tex ({len(questions_tex)} questions)")

if __name__ == "__main__":
    main()